"""Crash detection module package."""

from modules.crash_detection.detector import CrashDetector
from modules.crash_detection.thresholds import (
    ACCELERATION_HIGH_THRESHOLD,
    ACCELERATION_MEDIUM_THRESHOLD,
    ACCELERATION_WARNING_THRESHOLD,
    IMPACT_FORCE_HIGH_THRESHOLD,
    IMPACT_FORCE_MEDIUM_THRESHOLD,
    IMPACT_FORCE_WARNING_THRESHOLD,
    ROLLOVER_ANGLE_THRESHOLD,
)

__all__ = [
    "CrashDetector",
    "ACCELERATION_WARNING_THRESHOLD",
    "ACCELERATION_MEDIUM_THRESHOLD",
    "ACCELERATION_HIGH_THRESHOLD",
    "IMPACT_FORCE_WARNING_THRESHOLD",
    "IMPACT_FORCE_MEDIUM_THRESHOLD",
    "IMPACT_FORCE_HIGH_THRESHOLD",
    "ROLLOVER_ANGLE_THRESHOLD",
]
